### ISSUE TITLE
Safari 9.1 (11601.5.17.1) - can't find Intl

### ISSUE THREAD

**Issue by obenjiro** [gothinkster/angular-realworld-example-app#1]
[Error] EXCEPTION: Error in ./FooterComponent class FooterComponent - inline template:3:30 caused by: Can't find variable: Intl
    handleError (main.bundle.js:41265)
    (anonymous function) (main.bundle.js:26943)
    invoke (main.bundle.js:82144)
    onInvoke (main.bundle.js:59805)
    invoke (main.bundle.js:82143)
    run (main.bundle.js:82037)
    (anonymous function) (main.bundle.js:82403)
    invokeTask (main.bundle.js:82177)
    onInvokeTask (main.bundle.js:59796)
    invokeTask (main.bundle.js:82176)
    runTask (main.bundle.js:82077)
    drainMicroTaskQueue (main.bundle.js:82309)
    invoke (main.bundle.js:82249)

**Comment by EricSimons** [comment]
I just tried in Safari 10, Chrome, Firefox and am unable to repro this issue. Did you `npm install`? If yes, perhaps removing node_nodules and trying again?

**Comment by aiboy** [comment]
I have that issue when i visit https://angular2.realworld.io

It's probably related to the fact that Safari 9.1 doesn't have Intl support.

http://caniuse.com/#search=Intl

Safari have 5.6% market share - it's not so small.

**Comment by EricSimons** [comment]
Got it. This is actually an open issue on the Angular CLI repo: #https://github.com/angular/angular-cli/issues/1675

For those wondering how to fix this: http://stackoverflow.com/questions/35017800/ionic-2-using-angular-2-pipe-breaks-on-ios-cant-find-variable-intl

We might go ahead and add the polyfill ourselves if the CLI team chooses to not include it by default in future versions, but we'll need to wait a bit and see what they decide on. Thanks for pointing this out!
