### ISSUE TITLE
Demo URL in readme is incorrect

### ISSUE THREAD

**Issue by zbarbuto** [gothinkster/angular-realworld-example-app#101]
Demo link in readme points to https://angular2.realworld.io/

It seems that the actual demo version us running at https://angular.realworld.io/ now

**Comment by Toxicable** [comment]
closed via ed3fdcc3e19b5a47b5830a46aff21815f8fe1a82

**Comment by jfcabral** [comment]
Hi, both of the links are not working for me... 😞

**Comment by Toxicable** [comment]
@jfcabral try now, looks like the deploy process is not perfect and wipes out the CNAME

**Comment by zbarbuto** [comment]
Link I was referring to was the "Demo" one in readme.

Have made a PR #105

**Comment by jfcabral** [comment]
Thank you @Toxicable, it's all good now 👍
