### ISSUE TITLE
Why is there no unsubscribe in ngOnDestroy?

### ISSUE THREAD

**Issue by splincode** [gothinkster/angular-realworld-example-app#107]
https://github.com/gothinkster/angular-realworld-example-app/blob/7074a491bbd61a52c40db525fa8c45d0145d7c00/src/app/article/article-comment.component.ts#L21

**Comment by juristr** [comment]
indeed I would add one in this component 🙂. you can submit a PR 🤓

**Comment by dmytrohridin** [comment]
@juristr look to PR please
