### ISSUE TITLE
Any news about Angular 6 migration ?

### ISSUE THREAD

**Issue by yiss** [gothinkster/angular-realworld-example-app#112]
I was wondering if there will be a migration to Angular 6 anytime soon

**Comment by hamzahamidi** [comment]
https://github.com/gothinkster/angular-realworld-example-app/pull/114

**Comment by hamzahamidi** [comment]
[Pr: Angular6-project-structure]( https://github.com/gothinkster/angular-realworld-example-app/pull/114
)
[Pr: Angular6-rxjs-dependencies-migration](https://github.com/gothinkster/angular-realworld-example-app/pull/115)

**Comment by yiss** [comment]
@hamzahamidi Im going to close it rn

**Comment by yiss** [comment]
You can close this issue

**Comment by guillermoarellano** [comment]
@letanloc1998 Please close this issue.

**Comment by guillermoarellano** [comment]
"Abandon all hope ye who participate here."

--------------
As an aside, there's a great post by Christopher Chedeau (@vjeux) about [some great learnings](https://blog.vjeux.com/2020/uncategorized/reflections-on-excalidraw.html) he found when he open-sourced his "Excalidraw" project. In it, he found that:

- Make it easy for people to contribute. 
- Respond quickly to issues.
- Elevate frequent contributors to maintainer roles.
- Be decisive about behavior-changing contributions.
- The owner is the quality gate.

I highly recommend open-source project owners read it.

**Comment by letanloc1998** [comment]
> @letanloc1998 Please close this issue.

What happened?
