### ISSUE TITLE
Switch auth to session/cookie based

### ISSUE THREAD

**Issue by fedebabrauskas** [gothinkster/angular-realworld-example-app#118]
What changes I need to do to work with cookies instead of jwt?
In the code, I saw a `populate()` method in `user.service.ts` that checks the localStorage for a token and then calls a get query to `/user` to fetch the current user data. IMO I only need to remove the jwt check and leave the query call, but I don't know.

**Comment by Islomkhodja** [comment]
How did you decide this?

**Comment by fedebabrauskas** [comment]
I didn't work anymore with this example 😞 
Anyway, I can help you, what is your doubt?
