### ISSUE TITLE
Best way to keep constants file

### ISSUE THREAD

**Issue by pradeep0508** [gothinkster/angular-realworld-example-app#125]
This style guide looks simple and nice. It would be really great if someone adds style guide for constants

**Comment by peterblazejewicz** [comment]
Just use TypeScript handbook as reference. AFAIK there is no styleguide in current Angular styleguide for constants/static variables conventions:
https://www.typescriptlang.org/docs/handbook/enums.html
There was a rule in older style guide though:
https://v2.angular.io/docs/ts/latest/guide/style-guide.html#!#03-02
Cheers!
