### ISSUE TITLE
[Explain about angular] F5 make not found error

### ISSUE THREAD

**Issue by lwf804** [gothinkster/angular-realworld-example-app#141]
Hi, I am beginner with angular2. I try with your demo: `https://angular.realworld.io`. But when i press F5 at url: `https://angular.realworld.io/profile/travelLX`. This act make not found error. Can you explain for me? Thanks!

**Comment by LordMidi** [comment]
Because the webserver (hosting the app) tries to serve the route. It must be configured that the requests https://angular.realworld.io/xxxx respond with the angular index.html which will take control of the routing to /profile/travelLX

**Comment by geromegrignon** [comment]
fixed
