### ISSUE TITLE
Tag wrap isn't handled well

### ISSUE THREAD

**Issue by 1nv1n** [gothinkster/angular-realworld-example-app#143]
When there are a lot of tags for an article, the manner in which they're displayed on the UI makes it such that some tags overflow onto the next article's space & the "like" counter gets moved.

![AngularRealWorldIOTags](https://user-images.githubusercontent.com/3885804/54620028-8d8b1280-4a33-11e9-9dab-a2537b0fdfba.PNG)

Can be replicated (as of now) by going to the home page & clicking on any of the tags that appear on the image above.

**Comment by peterblazejewicz** [comment]
We could probably send an dm to Thinkster, the CSS style should be open sourced as it begs for:
- update (its' on BS 4 alpha)
- fixes
/cc @joeeames

**Comment by joeeames** [comment]
is there something I need to do here?

**Comment by peterblazejewicz** [comment]
@joeeames 
I'm really sorry for bothering you, I was wrong who to involve 🙇

**Comment by peterblazejewicz** [comment]
@anishkny 
Can you ping me about this part of the project:
https://github.com/gothinkster/conduit-bootstrap-template
Thanks!
