### ISSUE TITLE
Setting baseUrl in protractor.conf.js is not working with Remote URL

### ISSUE THREAD

**Issue by hanatharesh2712** [gothinkster/angular-realworld-example-app#146]
I want to set remote URL and run the tests against it. so, I am setting up baseUrl(e.g. www.google.com) in protractor.conf.js file but it does not work.

Repro steps
•	In a new Angular Cli project, in the e2e folder open protractor.conf.js
•	change baseUrl to https://google.com
•	run ng e2e

Observed behaviour
The browser opens up to http://localhost:4200/ and not https://google.com

Desired behaviour
I think it should go to what the baseurl is set to.

Please help. Thanks in advance!

**Comment by peterblazejewicz** [comment]
https://github.com/angular/angular-cli/issues/11089

**Comment by Progdrasil** [comment]
> [angular/angular-cli#11089](https://github.com/angular/angular-cli/issues/11089)

I'm having a similar issue running end to end tests within my CI configuration. similarly to [this comment](https://github.com/angular/angular-cli/issues/11089#issuecomment-469930449). Unfortunately that issue is locked.
