### ISSUE TITLE
502 Error from backend

### ISSUE THREAD

**Issue by Postavshik** [gothinkster/angular-realworld-example-app#190]
Backend returns 502 error
![image](https://user-images.githubusercontent.com/21285622/101362076-424b1000-3865-11eb-95eb-ffe5524b5696.png)

**Comment by cirosantilli** [comment]
I don't reprodue on this backend: https://github.com/cirosantilli/node-express-sequelize-realworld-example-app/tree/5a7dd08ca8333f0a34357df9f86d7b506f610ed9
