### ISSUE TITLE
Changing profile does not changing "edit profile" and "follow"

### ISSUE THREAD

**Issue by arrowwu** [gothinkster/angular-realworld-example-app#20]
When I am on my profile, i see "" Edit profile settings", then I click on my feed's profile name, i am still see "Edit profile settings", however it should be "Follow xxx"

**Comment by arrowwu** [comment]
Look like boolean isUser was not updated, so you have to refresh the browser to update it

**Comment by tiddy** [comment]
https://github.com/gothinkster/angular-realworld-example-app/pull/14

**Comment by arrowwu** [comment]
Thanks
