### ISSUE TITLE
No articles are here... yet. CSS broken, shows up in bad location

### ISSUE THREAD

**Issue by cirosantilli** [gothinkster/angular-realworld-example-app#202]
9e8c49514ee874e5e0bbfe53ffdba7d2fd0af36f

![Screenshot from 2021-07-01 10-53-28](https://user-images.githubusercontent.com/1429315/124104860-97957b80-da5a-11eb-8c29-927a4479af86.png)

Expected good e.g. from https://github.com/gothinkster/react-redux-realworld-example-app/tree/9186292054dc37567e707602a15a0884d6bdae35

![Screenshot from 2021-07-01 10-53-45](https://user-images.githubusercontent.com/1429315/124104954-abd97880-da5a-11eb-9fb7-acf55dacca20.png)

The fix is likely to add `div class="article-preview"`.

**Comment by geromegrignon** [comment]
fixed
