### ISSUE TITLE
 Global Feed Article

### ISSUE THREAD

**Issue by PetkovSvetoslav** [gothinkster/angular-realworld-example-app#235]
Hi good Angular app, but how to delete Global Feed Article on Home Page? where they stored? how to change them? from some profil: Magda Parry?

**Comment by geromegrignon** [comment]
Hi @PetkovSvetoslav, those articles have been added as fake articles from fake accounts for demonstration purposes. There are stored in public api.realworld.io API.
There are not meant to be changed as you can only change articles from your own account.
