### ISSUE TITLE
duplicate navbar once the user is logged in

### ISSUE THREAD

**Issue by JavaZakariae** [gothinkster/angular-realworld-example-app#259]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/34305250/236565864-3fd9ac83-e35d-471e-a140-4a6c3447a159.png">

The     <ul *appShowAuthed="true" class="nav navbar-nav pull-xs-right"> is renderer many times.
 To reproduce the bug:
- After the user is logged in, and the user click successively on new article->Home ->new article->Home 
The nav bar is duplicated as shown in the image.

Is the bug related to the fact that we are not unsubscribing from the observable:

```
import {
  Directive,
  Input,
  OnInit,
  TemplateRef,
  ViewContainerRef,
} from "@angular/core";
import { UserService } from "../core/services/user.service";

@Directive({
  selector: "[appShowAuthed]",
  standalone: true,
})
export class ShowAuthedDirective implements OnInit {
  constructor(
    private templateRef: TemplateRef<any>,
    private userService: UserService,
    private viewContainer: ViewContainerRef
  ) {}

  condition: boolean = false;

  ngOnInit() {
    this.userService.isAuthenticated.subscribe((isAuthenticated: boolean) => {
      if (
        (isAuthenticated && this.condition) ||
        (!isAuthenticated && !this.condition)
      ) {
        this.viewContainer.createEmbeddedView(this.templateRef);
      } else {
        this.viewContainer.clear();
      }
    });
  }

  @Input() set appShowAuthed(condition: boolean) {
    this.condition = condition;
  }
}

```

**Comment by shambhu-22** [comment]
I found some issue in the ngOnInit() of editor.component.ts if we comment it, the duplication of nav links does not happen, checking to make it work there, if i get will ping

**Comment by geromegrignon** [comment]
@JavaZakariae Thanks for the report: the problem was the existing view was not checked before adding it.

@shambhu-22 the `get` function is using a slug already. Feel free to add more context if needed.
