### ISSUE TITLE
Fix cloning issue

### ISSUE THREAD

**Issue by MxolisiSibaya322** [gothinkster/angular-realworld-example-app#277]
When cloning using http...I get this error 

Cloning into 'angular-realworld-example-app'...
remote: Enumerating objects: 1554, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (39/39), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 3861 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by geromegrignon** [comment]
Unrelated to the project itself but network connection stability.
