### ISSUE TITLE
fatal:could not read from the repository

### ISSUE THREAD

**Issue by Mugunthan93** [gothinkster/angular-realworld-example-app#28]
hi..

when i put this command in my cli...

"**git clone git@github.com:gothinkster/angular2-realworld-example-app.git**"

it gives this error

Warning:permanently added to the RSA host key for the IP address "**my ip address**" to the list of known host

permission denied<public key>

please make sure you have the correct access rights and the repository exists

**Comment by juristr** [comment]
Hmm, this is a public GitHub repo, so cloning should work just fine. In case let me know again.
