### ISSUE TITLE
Two Images links are broken on README.md

### ISSUE THREAD

**Issue by arunpratap26** [gothinkster/angular-realworld-example-app#285]
There are two screenshot on README.md file but they are broken  i tried it on both Chrome and Firefox 
![image](https://github.com/user-attachments/assets/e785d8ba-d5ec-4d3c-b495-65aa5de3ba8a)
![image](https://github.com/user-attachments/assets/2a00f73a-f63c-4079-a50f-19500556f0fd)

**Comment by geromegrignon** [comment]
Hi @arunpratap26, thanks for the report.
I removed them as outdated.
