### ISSUE TITLE
Demo URL -

### ISSUE THREAD

**Issue by pgcdev** [gothinkster/angular-realworld-example-app#300]
Your link for demo is broken, as of 9th Dec 2024.
This is the url -> https://angular.realworld.io/

It's serving nothing. What am I supposed to look at?
Pl resolve this!

**Comment by geromegrignon** [comment]
Demo link removed as the demo is not served anymore.

**Comment by prestopasto** [comment]
@geromegrignon There is still a link to the demo site under the ```## Functionality overview``` section.
