### ISSUE TITLE
Access-control-allow-origin error with flask local backend

### ISSUE THREAD

**Issue by nikhilkul** [gothinkster/angular-realworld-example-app#34]
I ended up installing chrome extension to "access-control-allow-origin"

**Comment by mohamed-aziz** [comment]
This has nothing to do with this project, you just have to edit the whitelist variable, it's not there by default but b7754cc28033f69a26e2581eb519b33aa115cbfc fixes it.

**Comment by nikhilkul** [comment]
Thanks. The [README](https://github.com/gothinkster/angular-realworld-example-app/edit/master/README.md) here is super helpful and I was able to reproduce everything within seconds. With this fix, the whole setup is completely reproducible.  🥂
