### ISSUE TITLE
Get calls to http://localhost:4200/null

### ISSUE THREAD

**Issue by nikhilkul** [gothinkster/angular-realworld-example-app#35]
Not sure why this appears in my console whenever I post a comment or whenever I publish a new article.

`null:1 GET http://localhost:4200/null`

**Comment by irfanmayo0786** [comment]
i also found this same error

**Comment by celikmustafa89** [comment]
it works for the online example. 
I guess you are running the project on your local environment. So, It may not have the backend side of comment and article stuff.

@irfanmayo0786  where are you from?(Türk müsün?)

**Comment by irfanmayo0786** [comment]
im form pakistan. if you are full stack developer kindly tell me your email thanks in advance @celikmustafa89

**Comment by celikmustafa89** [comment]
@irfanmayo0786 I'm from Turkey. I am interested in full stack development.
here is my email celikmustafa89@gmail.com.
we can communicate via email or hangouts.
Nice to meet you.

**Comment by irfanmayo0786** [comment]
Salaam brother,
im working in company here in lahore. i worked in php.
same nice to meet you brother

**Comment by Samhot** [comment]
For those who have this error and still don't know why, it's because you or another user don't have a profile picture. Simply set an image in your profile and the error will disappear.
