### ISSUE TITLE
Tag not saving when publishing articles

### ISSUE THREAD

**Issue by skopekreep** [gothinkster/angular-realworld-example-app#45]
When the 'Publish Article" button pressed, an entered tag is not saved to the database. Currently the only way to save a tag is by typing it in the tag field and hitting the Enter key.

It is arguable that a more natural and intuitive editing workflow involves adding/editing content (including tags) and saving all additions/edits with the single click of the 'Publish Article' button.

### ___** A [pull request](https://github.com/gothinkster/angular-realworld-example-app/pull/44) has been submitted to rectify this issue. **___

**Comment by iravitejakumar** [comment]
#102 resolved the issue.

**Comment by Toxicable** [comment]
fixed via 01f1640b44100a3313cc05d9bcda16f00eae4154
