### ISSUE TITLE
App being benchmarked is in Development mode

### ISSUE THREAD

**Issue by MarkPieszak** [gothinkster/angular-realworld-example-app#51]
From the console:
> Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

This will severely impact benchmarking results, it should be prod / AoT'd / etc.

**Comment by EricSimons** [comment]
@markpieszak just merged that PR - what benchmarks are you referring to btw? This repo was primarily designed for edu purposes, so prob not great for doing benchmarking stuff/etc!

**Comment by MarkPieszak** [comment]
What up Eric! :wave: How's it going!?
This article here, looks like they used it in this article here 😢 

I'll close this out then, thanks man
