### ISSUE TITLE
Angular 5 Update

### ISSUE THREAD

**Issue by NilsNaegele** [gothinkster/angular-realworld-example-app#54]
It might be a good idea to update the code to the newest version of Angular?

An Angular Material 5 implementation too?

Also a Bootstrap 4 version, would be nice?

**Comment by mountpoint** [comment]
+1

**Comment by Toxicable** [comment]
done via https://github.com/gothinkster/angular-realworld-example-app/commit/044c174f24f6971f00b62ed2d499600f10f6b4dd
