### ISSUE TITLE
Updated to latest versions and best practices

### ISSUE THREAD

**Issue by Toxicable** [gothinkster/angular-realworld-example-app#55]
Just took a quick look through the project and noticed a few things that could do with updating so that we're up to update with the latest versions and best practices.
- [x] Updated to to v5
- [ ] Move subscribes to `| async` where appropriate 
- [x] Update to rxjs v5.5 and use lettables
- [x] Add a linter (prittifier?)
- [x] Swap `Http` for `CttpClient`
- [ ] Add Unit and e2e tests
- [x] component selector prefixing
- [ ] classes -> interfaces
- [x] `(<any>Object)` -> `Object`
- [x] remove nested subscribes

**Comment by juristr** [comment]
👍 Going to do the upgrade to `v5` including CLI changes

**Comment by juristr** [comment]
Also, there are no tests, so adding tests would be nice as well 😉

**Comment by juristr** [comment]
@EricSimons If you have some time to look at the referenced PRs here & possibly merge them would be cool. It's the Angular GDE squat working here, commandeered by @StephenFluin 😂

**Comment by EricSimons** [comment]
@juristr so sorry about the delay, been afk a ton the past few days 😅 Thanks so much for putting together these PR's!! Just merged 👍

**Comment by juristr** [comment]
@EricSimons no worries man, I was just kidding 😉. Hopefully me or @Toxicable can submit some further PRs to also adjust the remaining "issues"

**Comment by Toxicable** [comment]
Yup, ill be doing the rxjs 5.5 / lettables later this evening

**Comment by irfanmayo0786** [comment]
@Toxicable this app is now fully in angular5. Can you please describe me main things that are not yet in ng-5.

**Comment by Toxicable** [comment]
@irfanmayo0786 I'm confused, this example app is using Angular v5

**Comment by irfanmayo0786** [comment]
my mean is that this app was first in angular-2. I'm just asking now it's fully updated in angular 5.

**Comment by juristr** [comment]
@irfanmayo0786 Yep, it's now using Angular 5 (as of [this commit](https://github.com/gothinkster/angular-realworld-example-app/commit/044c174f24f6971f00b62ed2d499600f10f6b4dd)). What's still missing are the points at the very beginning of this issue which haven't been checked yet. Those are more like best practices that should be implemented in Angular version 5 apps.

**Comment by irfanmayo0786** [comment]
thanks @juristr

**Comment by Toxicable** [comment]
Closing this since most of what was here is done.
The other things have their own issues

**Comment by wilfredonoyola** [comment]
Hi @Toxicable I would like to  Add Unit and e2e tests.

**Comment by Toxicable** [comment]
@wilfredonoyola I don't have a plan.
Feel free to send us a PR

**Comment by juristr** [comment]
For e2e tests I'd consider using Cypress instead of Protractor.
