### ISSUE TITLE
Pages divided on module?

### ISSUE THREAD

**Issue by truefunrun** [gothinkster/angular-realworld-example-app#70]
Sorry, I have a question about dividing routes on modules

Each module load separately ?
When we're going to our app we're loading Home module and If we're going to Setting page and we're loading Settings module, it is?

**Comment by juristr** [comment]
@truefunrun Hey. Yep, pretty much. Usually you structure you Angular application in different feature areas, just as in this app:

![image](https://user-images.githubusercontent.com/542458/35124420-5461767e-fca6-11e7-9809-30026985530e.png)

Each of these modules might then also contribute its own routings via `RouterModule.forChild([...])`, and might even be lazy loaded. Here are some links which are helpful:

- https://angular.io/guide/router#refactor-the-routing-configuration-into-a-routing-module
- https://angular.io/guide/lazy-loading-ngmodules

_Note, this repo isn't yet structured according to the "Router Module Pattern" (as suggested [here](https://angular.io/guide/router#refactor-the-routing-configuration-into-a-routing-module)). That can be future work 😉_

Let me know if you have any further questions. Closing the issue for now, but feel free to open it again in case.

**Comment by truefunrun** [comment]
@juristr thank you!
