### ISSUE TITLE
multiple errors

### ISSUE THREAD

**Issue by X-Anonymous-Y** [gothinkster/angular-realworld-example-app#71]
see the pictures below!

the default page is OK
[default route](https://imgur.com/a/iVMeL)

Wrong data loaded!
all posts are displayed instead of user posts
[profile route](https://imgur.com/a/6Rkp1)

Wrong data loaded!
all posts are displayed instead of taged posts
[tags route](https://imgur.com/a/Iqwo8)

I am using the latest version of:
[Laravel](https://github.com/gothinkster/laravel-realworld-example-app)
and:
[Angular](https://github.com/gothinkster/angular-realworld-example-app)

I hope you understand my problem

Sorry for the Bad English

**Comment by X-Anonymous-Y** [comment]
@hamzahamidi 

which version do you use?
at version 5.2.9 these errors appear!

**Comment by jafaircl** [comment]
I forked the repo, built it in production mode and threw it on netlify and these errors are showing up. See an example here: https://angular-realworld-example-app.netlify.com/

Here is the forked repo: https://github.com/jafaircl/angular-realworld-example-app

 The only thing different is built dist folder.

**Comment by juristr** [comment]
> Wrong data loaded!
all posts are displayed instead of user posts
profile route

> Wrong data loaded!
all posts are displayed instead of taged posts
tags route

Yep, indeed. these are probably bugs. We'd have to debug you service that loads the data and whether it correctly filters it

**Comment by juristr** [comment]
> I forked the repo, built it in production mode and threw it on netlify and these errors are showing up. See an example here: https://angular-realworld-example-app.netlify.com/

Which errors do you mean?

**Comment by jafaircl** [comment]
@juristr the same ones that @X-Anonymous-Y mentioned.

**Comment by jafaircl** [comment]
@juristr after looking at it, it's a quick fix. In articles.service.ts, `new HttpParams(params)` should be `new HttpParams({ fromObject: params })`

I can do a pull request if you want. There are one or two other things I saw that could be improved (lazy loading, dynamic imports, etc).

**Comment by juristr** [comment]
Lazy loading via the router landed yesterday 👌

**Comment by X-Anonymous-Y** [comment]
works great now
