### ISSUE TITLE
Get HTTP 422 error when Register against https://conduit.productionready.io/api

### ISSUE THREAD

**Issue by pgbonino** [gothinkster/angular-realworld-example-app#81]
All running locally as I should. Apparently, it fetches articles and I can navigate through the public part of the application.

When I try to register, I get this error in console:

POST https://conduit.productionready.io/api/users 422 ()

Any clue?

I attach the complete request/response object catched from Network tab in Chrome debugger:
[register.txt](https://github.com/gothinkster/angular-realworld-example-app/files/1785028/register.txt)

**Comment by sanka2701** [comment]
chech [this](https://github.com/gothinkster/angular-realworld-example-app/issues/78)

**Comment by kurtdaveting** [comment]
@sanka2701 #80 does not the same error as @pgbonino

**Comment by dmytrohridin** [comment]
@kurtdaveting I had the same problems and it fixed them

**Comment by kurtdaveting** [comment]
@dmytrohridin will look more into it. I'm also having issues when i try to run the client connected to node api locally. However it throws me error 500 instead of 422 when signing up

**Comment by pgbonino** [comment]
@kurtdaveting I am also having error 500 when going against local node-express application. Particularly, it seems like the object is not being passed.

But for now I have just mentioned the problem when going against  https://conduit.productionready.io/api/users.

As soon as I have a minute, I will check what @sanka2701 said and let you know the results.

**Comment by pgbonino** [comment]
Hello,

I have updated to what said in #80 , but the behavour is the same. It is sending the request with `content-type:text/plain`.

Any other clue? Where else can I check to see why the requests are being sent in plain text instead of json?

**Comment by pgbonino** [comment]
@sanka2701, @kurtdaveting, definitely #80 close this too.

It was a matter of content-type set to plain text instead of json.

Thanks!!
