### ISSUE TITLE
Refresh token scenario

### ISSUE THREAD

**Issue by kevintanhongann** [gothinkster/angular-realworld-example-app#84]
I was checking out some implementations on JWT regarding refresh tokens and I didn't manage to find it being simulated here. Just thought I file something just so that someone can come to it later.

**Comment by b4youleap** [comment]
See open enhancement #22 - this would be covered by that. You may want to close this issue as a duplicate.

**Comment by kevintanhongann** [comment]
Okay sure. Duplicate #22
