### ISSUE TITLE
fix: live demo

### ISSUE THREAD

**Issue by jotatoledo** [gothinkster/angular-realworld-example-app#85]
Live demo shouldnt run on `devMode`.
Currently it does.

**Comment by juristr** [comment]
Seems like the codebase itself handles this already correctly:

https://github.com/gothinkster/angular-realworld-example-app/blob/master/src/main.ts#L7-L9

Most probably the app would simply have to be redeployed. #91 could help avoid these issues

**Comment by Toxicable** [comment]
fixed via 399804ae6f34b52dbe6eb097009f29641e538ef4
