### ISSUE TITLE
error : Cannot find module 'marked'.

### ISSUE THREAD

**Issue by YogeshSonar** [gothinkster/angular-realworld-example-app#87]
When im clone this application and after Run the >npm install it will install all necessary module after that finally i'm going to run the application then it will show the error.

ERROR in src/app/article/markdown.pipe.ts(2,25): error TS2307: Cannot find module 'marked'.

Please fix these.

Thanx in advance.

**Comment by Toxicable** [comment]
fixed via https://github.com/gothinkster/angular-realworld-example-app/commit/4eebdf5637cbed5f68c047ae2a06242c7f0dd78d
