### ISSUE TITLE
New feature: CI github-pages with Travis-ci

### ISSUE THREAD

**Issue by hamzahamidi** [gothinkster/angular-realworld-example-app#91]
I have a ready PR for Continuous Integration in github-pages with Travis-ci If you're interested.

**Comment by juristr** [comment]
Sounds interesting. Don't know how the app is currently being deployed to here: https://angular2.realworld.io/#/

@Toxicable any idea?

**Comment by Toxicable** [comment]
Need @EricSimons To handle this one

**Comment by juristr** [comment]
👍 Also the one I linked #85

**Comment by hamzahamidi** [comment]
All we need is for the owner to have a Travis account & to generate a GitHub token for public repositories. The deployment will be in a branch called gh-pages & the url will be https://gothinkster.github.io/angular-realworld-example-app  
When that is done, it will be easier to make this app a PWA if you're interested.

**Comment by EricSimons** [comment]
Hey all- been fighting a flu the past 48hrs, sorry about my delay here.

I think this is an AWESOME idea @hamzahamidi- lets do it!

I just enabled travis for this repo- @juristr & @Toxicable I just set you as admins on this repo, do you think you could get the GH pages branch/etc set up?

I also just pointed angular.realworld.io to our github pages url, so whenever the GH pages branch gets published it should be live 👍

**Comment by juristr** [comment]
@EricSimons oh, hope you feel better now.

We should be able to get this going. @hamzahamidi, can you provide a PR with the corresponding configuration so we can have a look at it?

**Comment by hamzahamidi** [comment]
Sounds great! I'm on it. Do you have a chat suggestion to discuss this?

**Comment by hamzahamidi** [comment]
One more question, which branch you deploy is it master?

**Comment by Toxicable** [comment]
Deployed here https://gothinkster.github.io/angular-realworld-example-app/
