### ISSUE TITLE
Use Production Build in Demo Mode 

### ISSUE THREAD

**Issue by GulajavaMinistudio** [gothinkster/angular-realworld-example-app#92]
I checking Angular Realworld Demo, but after i check in Inspect Element in Network Tab , this demo is not using production mode or production build. And the result is not fast as production mode.

Try run Production Build with this command 
`ng build --prod --build-optimizer`

Docs
https://angular.io/guide/deployment

**Comment by manishjanky** [comment]
This will really impact the metrics as. In production mode with aot angular compiler is not loaded in the browser and compilation is done at build time. 
Thus reducing the chunk size as well as improves the performance as the compilation is not happening in the browser which is the case with the current build of this application.

**Comment by juristr** [comment]
The production build is already made. What the current scripts don't do is to run the build optimizer.

https://github.com/gothinkster/angular-realworld-example-app/blob/master/package.json#L8

@GulajavaMinistudio could you test this out locally and in case submit a PR?

**Comment by Toxicable** [comment]
Build optimizer is enabled by default on the current version of the cli

**Comment by Toxicable** [comment]
@juristr Im not sure on that one, Might have been around 1.5 or 1.6 at a guess.

**Comment by Toxicable** [comment]
closed via 399804ae6f34b52dbe6eb097009f29641e538ef4

**Comment by GulajavaMinistudio** [comment]
Many thanks for response :)
