### ISSUE TITLE
Issue loading "my posts"

### ISSUE THREAD

**Issue by AlexJFishman** [gothinkster/angular-realworld-example-app#99]
When loading "my posts" from a profile the Http params are empty, 
which means it loads without a query ( full feed list ).

I fixed it by changing the "apiService" get method to :

`get(path: string, data = {} ): Observable<any> {
    const params: HttpParams = new HttpParams();
    return this._http.get(`${environment.api_url}${path}`, { params: data })
      .pipe(catchError(this.formatErrors));
  }`

**Comment by juristr** [comment]
Yep I noticed that wrong behavior. Could you provide a PR which fixes it? :)

**Comment by dmytrohridin** [comment]
@juristr  done
